/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arktrackerv4;

import javax.swing.JFrame;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class App extends JFrame implements ActionListener {
    
    CardLayout cardLayout;

    //Declare & Instantiate each world
    World testWorld = new World();

    public static void main(String[] args) {
        //Method to run application and open App Window
        App ArkTracker = new App("Ark Tracker V4");

    }

    App(String frameTitle) {
        super(frameTitle);
        // Instantiates & Sets layout of JFrame to cardLayout
        cardLayout = new CardLayout();
        setLayout(cardLayout);

        //Adds World Panels to the App Frame
        //TODO REMOVE
        add(testWorld, "test World");


        //End Contstructor with JFrame Settings
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        pack();
        setVisible(true);
        //Prevents Flickering issue that used to occur
        requestFocus();

    }

    @Override
    public void actionPerformed(ActionEvent e) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'actionPerformed'");
    }
}
